### ISSUE TITLE
Expand Supported Primitives in KmsClient Interface

### ISSUE THREAD

**Issue by ccobham** [tink-crypto/tink-java#14]
The current `KmsClient` interface only exposes the `Aead` primitive even though the underlying key management service may support other cryptographic operations.

Is there any interest in expanding the scope of the `KmsClient` interface to handle non-AEAD use cases?

**Current Implementation**

```java
public interface KmsClient {
  Aead getAead(String keyUri) throws GeneralSecurityException;
}
```

**Proposed Implementation**
```java
public interface KmsClient {

  <P> P getPrimitive(String keyUri, Class<P> targetClassObject) throws GeneralSecurityException;  

  @Deprecated
  default Aead getAead(String keyUri) throws GeneralSecurityException {
    return getPrimitive(keyUri, Aead.class);
  }
  
}
```

**Comment by tholenst** [comment]
Thank you for the suggestion. This isn't the solution which we will follow.

The KmsClient interface will become obsolete as there really shouldn't be any use for it, and we will replace it with direct instantiations of the primitive. Furthermore, the integrations will do this directly (so that there isn't really any need for tink-java to adapt).
